### ISSUE TITLE
select-all regardless of filters

### ISSUE THREAD

**Issue by kneissl** [mediakular/gridcraft#15]
When I have filters and select all, it seems to be selecting all entries regardless of filters. I've worked around it by doing a comparison between selectedRows.length and unpaged.length.
![image](https://github.com/user-attachments/assets/774c2423-e3e9-4f42-ab2c-47b8a3c6eff2)

**Comment by st3v3y** [comment]
Thank you for posting this.

Please confirm that the error is fixed in the latest version 0.2.9

**Comment by kneissl** [comment]
Looks like it works as expected now. Thanks!
