### ISSUE TITLE
Displaying GridFooter for Pagination before Grid breaks Pagination

### ISSUE THREAD

**Issue by ZaDarkSide** [mediakular/gridcraft#2]
If you ever want to render the Pagination before Grid Table for design purposes, the pagination breaks.
How the components are currently written don't allow moving the location of the Pagination before the Grid Table.
Maybe a refactoring using Svelte Stores or Svelte Contexts to allow this specific use case and make the overall code more flexible should be considered.

```svelte
<script lang="ts">
import { Grid, GridFooter, type GridColumn } from "@mediakular/gridcraft";
import { clients } from './clients.js';

let columns: GridColumn<Client>[] = [];

// Define paging variables
let itemsPerPage = 10;
let currentPage = 1;
let totalPages = 1;
let totalResults = 0;
</script>

<GridFooter bind:currentPage bind:totalPages bind:totalResults bind:itemsPerPage />
<Grid 
    data={clients} 
    {columns}
    bind:currentPage 
    bind:itemsPerPage 
    bind:totalPages 
    bind:totalResults />
```

[REPL Demo for simple paging before Grid](https://svelte.dev/repl/fe7713c6787b4642ba992ac6e04ccd9c?)

**Comment by st3v3y** [comment]
Hi @ZaDarkSide !
Thanks for your message. I hadn't noticed this bug. Moving the footer where ever you want was definitely the idea and should work. 
I will check how this can be fixed best, guessing stores would be a good approach.

**Comment by st3v3y** [comment]
Fixed in latest version
