### ISSUE TITLE
Using `bind:group={selectedRows}` causes infinite loop in some cases

### ISSUE THREAD

**Issue by ZaDarkSide** [mediakular/gridcraft#8]
Using `bind:group={selectedRows}` causes infinite loop in some cases

https://github.com/mediakular/gridcraft/blob/1ec5b33725bf526da62453755bf8487158a21b13/src/lib/components/Grid.svelte#L186-L188

Possible solution is to remove `bind:`
```svelte
 {#if showCheckboxes} 
     <svelte:component this={theme.grid.body.checkbox} value={row} index={gridData.indexOf(row)} group={selectedRows} /> 
                                                                                            <!-- ^^^^ -->
 {/if} 
```

**Comment by st3v3y** [comment]
Could you please post a case here in which this causes an infinite loop?

**Comment by ZaDarkSide** [comment]
Well are you sure you want to run this? It will freeze your browser...

Go to this example: https://svelte.dev/repl/c893a56fa13349029cef87a5fa8459c4

Then put this code in `App.svelte`

```svelte
<script>
    import { Grid } from '@mediakular/gridcraft'
    import { clients } from './clients.js'

    let showCheckboxes = false
</script>

<label for="showCheckboxes">
    <input type="checkbox" bind:checked={showCheckboxes} id="showCheckboxes"> Show checkboxes
</label>

<Grid data={clients} bind:showCheckboxes  />
```

Then click the `Show checkboxes` checkbox, it will totally freeze your browser...

**Comment by ZaDarkSide** [comment]
Also, I have joined Discord, we can talk there more.

**Comment by ZaDarkSide** [comment]
In your example if you add `0` value to `id` you can trigger the infinite loop.

![image](https://github.com/mediakular/gridcraft/assets/291278/aaf8dd02-9074-4a83-aabe-04890a126640)

Hope this helps track down the issue better.

**Comment by st3v3y** [comment]
> In your example if you add `0` value to `id` you can trigger the infinite loop.

This is a strange bug, but I fixed it in the latest [commit](https://github.com/mediakular/gridcraft/commit/5d367f45e8fe016e074bdfc3229914d6d8835764). 


But I think it is probably unrelated to: 

> Using bind:group={selectedRows} causes infinite loop in some cases

Which I also investigated but so far without success. I only know now that it is no solution to remove the `bind:`.

**Comment by ZaDarkSide** [comment]
Yes, the one you fixed it's probably unrelated to `bind:group={selectedRows}`, but both cases triggered an infinite loop, glad that one of them has been fixed already.

**Comment by ZaDarkSide** [comment]
Maybe the remaining issue with `bind:group={selectedRows}` could be a Svelte issue, maybe it should be asked upstream if they know any cases when Svelte goes into an infinite loop using `bind` ?

**Comment by st3v3y** [comment]
I fixed it. It happened when no ID was provided and I called a function to generate a new ID but unrelated to the row, so it endlessly generated new IDs; now I create a set of row => generated ID and use these ID when rendering the checkboxes/columns. Problem should be fixed in latest version
