### ISSUE TITLE
Using filtering while on page 2 will return wrong number of results

### ISSUE THREAD

**Issue by ZaDarkSide** [mediakular/gridcraft#9]
The issue happens when you for example are on a page is different than page 1 and you try to filter the items.

https://github.com/mediakular/gridcraft/blob/3bf26399db673e833b145efd7422504df6e53177/src/lib/GridFunctions.ts#L149-L162

Possible solution

```svelte
processPaging(groupBy: string, columns: GridColumn<T>[]): GridFunctions<T> { 
    this.dataUnpaged = [...this.data]; // <= this.dataUnpaged = Object.assign({}, this.data) maybe this is faster than spread to clone object with big data

    const currentPage = this.pagingData.currentPage; 
    const itemsPerPage = this.pagingData.itemsPerPage; 
  
    if (!groupBy) { 
        if (this.dataLength > itemsPerPage) { // do paging only if needed, if filtering returns less results than a page, this will probably fix the bug
            const startIndex = (currentPage - 1) * itemsPerPage; 
            const endIndex = startIndex + itemsPerPage; 

            this.data = this.data.slice(startIndex, endIndex);
         }
```

**Comment by st3v3y** [comment]
Thanks for reporting this issue. That must have happened when I changed the paging(-stores). I will investigate what's wrong.

> this.dataUnpaged = [...this.data]; // <= this.dataUnpaged = Object.assign({}, this.data) maybe this is faster than spread to clone object with big data

Do you have a reference that confirms that Object.assign({}, this.data) is faster? Your "maybe" made me skeptical :). I spent a little bit of time but didn't find any answer on what is faster.

> if (this.dataLength > itemsPerPage) { // do paging only if needed, if filtering returns less results than a page, this will probably fix the bug

This might be also an improvement, thanks for pointing it out! It might also "hide" the issue, but I think there is a different bug in there which I would like to find first.

**Comment by ZaDarkSide** [comment]
> Do you have a reference that confirms that Object.assign({}, this.data) is faster? Your "maybe" made me skeptical :). I spent a little bit of time but didn't find any answer on what is faster.

Hm..not really, but I think that was the case in the past, but now I see in newer benchmarks that all the JS runtimes optimized it heavily in the last years and it seems that spread is faster than `Object.assign` with newer versions of V8 and Node.js runtimes, but for very bigger data can't find proper benchmarks.

**Comment by st3v3y** [comment]
The filtering should work now after the latest [commit](https://github.com/mediakular/gridcraft/commit/b1fbb4bdc8f978ee34a4ff49a34fb986ada0aefe)
